### ISSUE TITLE
Boot is throwing `ClassNotFoundException`s

### ISSUE THREAD

**Issue by cndreisbach** [tailrecursion/boot#1]
I'm trying to use boot, and have used the `boot.edn` file from the Hoplon docs at http://hoplon.io/#/getting-started/.

Whenever I run `boot`, I get this stacktrace:

```
Exception in thread "main" java.lang.ExceptionInInitializerError
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:249)
    at clojure.lang.RT.loadClassForName(RT.java:2098)
    at clojure.lang.RT.load(RT.java:430)
    at clojure.lang.RT.load(RT.java:411)
    at clojure.core$load$fn__5018.invoke(core.clj:5530)
    at clojure.core$load.doInvoke(core.clj:5529)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.core$load_one.invoke(core.clj:5336)
    at clojure.core$load_lib$fn__4967.invoke(core.clj:5375)
    at clojure.core$load_lib.doInvoke(core.clj:5374)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invoke(core.clj:619)
    at clojure.core$load_libs.doInvoke(core.clj:5413)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:619)
    at clojure.core$require.doInvoke(core.clj:5496)
    at clojure.lang.RestFn.invoke(RestFn.java:512)
    at tailrecursion.boot$loading__4910__auto__.invoke(boot.clj:9)
    at tailrecursion.boot__init.load(Unknown Source)
    at tailrecursion.boot__init.<clinit>(Unknown Source)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:249)
    at clojure.lang.RT.loadClassForName(RT.java:2098)
    at clojure.lang.RT.load(RT.java:430)
    at clojure.lang.RT.load(RT.java:411)
    at clojure.core$load$fn__5018.invoke(core.clj:5530)
    at clojure.core$load.doInvoke(core.clj:5529)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.core$load_one.invoke(core.clj:5336)
    at clojure.core$load_lib$fn__4967.invoke(core.clj:5375)
    at clojure.core$load_lib.doInvoke(core.clj:5374)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invoke(core.clj:619)
    at clojure.core$load_libs.doInvoke(core.clj:5413)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:619)
    at clojure.core$require.doInvoke(core.clj:5496)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at tailrecursion.boot.loader$_main.doInvoke(loader.clj:65)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at tailrecursion.boot.loader.main(Unknown Source)
Caused by: java.lang.ClassNotFoundException: java.nio.file.FileSystems
    at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:171)
    at tailrecursion.boot.gitignore$loading__4910__auto__.invoke(gitignore.clj:9)
    at tailrecursion.boot.gitignore__init.load(Unknown Source)
    at tailrecursion.boot.gitignore__init.<clinit>(Unknown Source)
    ... 42 more
```

**Comment by alandipert** [comment]
Are you on JDK 6?  java.nio.file is in JDK7, and it looks like we require
it.  Please try with JDK7 and let us know how it goes.
Alan

**Comment by cndreisbach** [comment]
That is, in fact, it. Thanks!
