### ISSUE TITLE
boot repl crashed on exit

### ISSUE THREAD

**Issue by jumblerg** [tailrecursion/boot#34]
after hacking about in the repl a bit, i typed exit, then ^C, then ^C, then ^C:

``` clojure
boot.user=> exit
NoClassDefFoundError net/cgrand/parsley/lrplus/TableState$reify__2701
    net.cgrand.parsley.lrplus.TableState (lrplus.clj:23)
    clojure.lang.KeywordLookupSite.install (KeywordLookupSite.java:52)
    clojure.lang.KeywordLookupSite.fault (KeywordLookupSite.java:26)
    net.cgrand.parsley.lrplus/step1 (lrplus.clj:165)
    net.cgrand.parsley.lrplus/step (lrplus.clj:190)
    net.cgrand.parsley/stepper/self--3577 (parsley.clj:39)
    net.cgrand.parsley/stepper/self--3577 (parsley.clj:36)
    reply.parsing/reparse (parsing.clj:25)
    reply.parsing/parsed-forms (parsing.clj:62)
    reply.eval-modes.nrepl/run-repl (nrepl.clj:131)
    reply.eval-modes.nrepl/main (nrepl.clj:233)
    reply.main/launch-nrepl/fn--4269 (main.clj:78)
Caused by:
ClassNotFoundException net.cgrand.parsley.lrplus.TableState$reify__2701
    java.net.URLClassLoader$1.run (URLClassLoader.java:366)
    java.net.URLClassLoader$1.run (URLClassLoader.java:355)
    java.security.AccessController.doPrivileged (AccessController.java:-2)
    java.net.URLClassLoader.findClass (URLClassLoader.java:354)
    java.lang.ClassLoader.loadClass (ClassLoader.java:424)
    java.lang.ClassLoader.loadClass (ClassLoader.java:357)
    net.cgrand.parsley.lrplus.TableState (lrplus.clj:23)
    clojure.lang.KeywordLookupSite.install (KeywordLookupSite.java:52)
Bye for now!
Exception in thread "main" java.lang.NoClassDefFoundError: boot/main$_main$fn__809
    at boot.main$_main.invoke(main.clj:76)
    at clojure.lang.Var.invoke(Var.java:379)
    at org.projectodd.shimdandy.impl.ClojureRuntimeShimImpl.invoke(ClojureRuntimeShimImpl.java:91)
    at org.projectodd.shimdandy.impl.ClojureRuntimeShimImpl.invoke(ClojureRuntimeShimImpl.java:84)
    at boot.App.main(App.java:185)
Caused by: java.lang.ClassNotFoundException: boot.main$_main$fn__809
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 5 more
Exception in thread "SIGINT handler" java.lang.NoClassDefFoundError: reply/eval_modes/nrepl$handle_client_interruption_BANG_$fn__3843$fn__3844
    at reply.eval_modes.nrepl$handle_client_interruption_BANG_$fn__3843.invoke(nrepl.clj:37)
    at reply.eval_modes.nrepl.proxy$java.lang.Object$SignalHandler$d8c00ec7.handle(Unknown Source)
    at sun.misc.Signal$1.run(Signal.java:212)
    at java.lang.Thread.run(Thread.java:724)
Caused by: java.lang.ClassNotFoundException: reply.eval_modes.nrepl$handle_client_interruption_BANG_$fn__3843$fn__3844
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 4 more
Exception in thread "SIGINT handler" java.lang.NoClassDefFoundError: reply/eval_modes/nrepl$handle_client_interruption_BANG_$fn__3843$fn__3844
    at reply.eval_modes.nrepl$handle_client_interruption_BANG_$fn__3843.invoke(nrepl.clj:37)
    at reply.eval_modes.nrepl.proxy$java.lang.Object$SignalHandler$d8c00ec7.handle(Unknown Source)
    at sun.misc.Signal$1.run(Signal.java:212)
    at java.lang.Thread.run(Thread.java:724)
Exception in thread "SIGINT handler" java.lang.NoClassDefFoundError: reply/eval_modes/nrepl$handle_client_interruption_BANG_$fn__3843$fn__3844
    at reply.eval_modes.nrepl$handle_client_interruption_BANG_$fn__3843.invoke(nrepl.clj:37)
    at reply.eval_modes.nrepl.proxy$java.lang.Object$SignalHandler$d8c00ec7.handle(Unknown Source)
    at sun.misc.Signal$1.run(Signal.java:212)
    at java.lang.Thread.run(Thread.java:724)
Exception in thread "SIGINT handler" java.lang.NoClassDefFoundError: reply/eval_modes/nrepl$handle_client_interruption_BANG_$fn__3843$fn__3844
    at reply.eval_modes.nrepl$handle_client_interruption_BANG_$fn__3843.invoke(nrepl.clj:37)
    at reply.eval_modes.nrepl.proxy$java.lang.Object$SignalHandler$d8c00ec7.handle(Unknown Source)
    at sun.misc.Signal$1.run(Signal.java:212)
    at java.lang.Thread.run(Thread.java:724)
```

**Comment by jumblerg** [comment]
this issue occurred prior to the aot'd boot release; i'm unable to reproduce with the latest version.  review and close if it makes sense to do so.

**Comment by jumblerg** [comment]
after discussion with @micha, determined this issue was most likely caused by upgrading boot jars while an older version was running.
