### ISSUE TITLE
handle authentication exception when connection to private repo fails

### ISSUE THREAD

**Issue by jumblerg** [tailrecursion/boot#39]
SEVERE: Request Failed.
org.jets3t.service.S3ServiceException: S3 Error Message. GET '/snapshot%2Ftailrecursion%2Fclojure-adapter-servlet%2F0.1.0-SNAPSHOT%2Fmaven-metadata.xml' on Host '<my>.repository.s3.amazonaws.com' @ 'Fri, 03 Oct 2014 15:30:57 GMT' -- ResponseCode: 403, ResponseStatus: Forbidden, XML Error Message: <?xml version="1.0" encoding="UTF-8"?><Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>E7EDF9C66A8B855D</RequestId><HostId>U40MhHaosnmvEeU0X8l6wOpNbNY75pcRHaiN6ELQaREnknbQi5bKkRTSdWRPugIK</HostId></Error>
    at org.jets3t.service.impl.rest.httpclient.RestS3Service.performRequest(RestS3Service.java:441)
    at org.jets3t.service.impl.rest.httpclient.RestS3Service.performRestGet(RestS3Service.java:876)
    at org.jets3t.service.impl.rest.httpclient.RestS3Service.getObjectImpl(RestS3Service.java:1712)
    at org.jets3t.service.impl.rest.httpclient.RestS3Service.getObjectImpl(RestS3Service.java:1655)
    at org.jets3t.service.S3Service.getObject(S3Service.java:2215)
    at org.jets3t.service.S3Service.getObject(S3Service.java:1424)
    at org.springframework.aws.maven.SimpleStorageServiceWagon.getResource(SimpleStorageServiceWagon.java:93)
    at org.springframework.aws.maven.AbstractWagon.get(AbstractWagon.java:184)
    at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$GetTask.run(WagonRepositoryConnector.java:601)
    at org.sonatype.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:60)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:724)

**Comment by micha** [comment]
I think this is a documented issue with the s3 wagon implementation. From the [README](https://github.com/technomancy/s3-wagon-private):

> Note that deploying an artifact that doesn't already exist will cause an org.jets3t.service.S3ServiceException stack trace to be emitted; this is a bug in one of the underlying libraries but is harmless.
